version: '3.8'

services:

  server:
    container_name: server
    image: node:20.15
    volumes:
      - .:/app
    tty: true
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@database:5432/${DB_DATABASE}
    depends_on:
      - database
    
  database:
    container_name: database
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432